# Generated by Django 5.1.4 on 2025-03-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories_content', models.FileField(upload_to='content_stories')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stories_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_connect_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_author_comment', to=settings.AUTH_USER_MODEL)),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_comment', to='stories.stories')),
            ],
        ),
        migrations.CreateModel(
            name='StoriesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stories_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_stories', to='stories.stories')),
            ],
        ),
        migrations.CreateModel(
            name='StoriesLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stories_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_stories', to='stories.stories')),
            ],
            options={
                'unique_together': {('author', 'stories_connect')},
            },
        ),
    ]
