# Generated by Django 5.1.3 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LikePosst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img1', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img2', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img3', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img4', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img5', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img6', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img7', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img8', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img9', models.FileField(blank=True, null=True, upload_to='post_img')),
                ('post_img10', models.FileField(blank=True, null=True, upload_to='post_img')),
            ],
        ),
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
